# builder-config.yaml - With custom exporter (matching your v0.128.0 setup)
dist:
  name: custom-otelcol
  description: Custom OpenTelemetry Collector v0.128.0 (Kubernetes-enabled + Custom Exporter)
  output_path: ./custom-collector
  otelcol_version: 0.128.0

exporters:
  - gomod: go.opentelemetry.io/collector/exporter/debugexporter v0.128.0
  - gomod: go.opentelemetry.io/collector/exporter/otlpexporter v0.129.0
  - gomod: go.opentelemetry.io/collector/exporter/otlphttpexporter v0.128.0
  # Your custom exporter - path to local module
  - gomod: customexporter v0.1.0
    path: ./custom-exporter

processors:
  - gomod: go.opentelemetry.io/collector/processor/batchprocessor v0.128.0
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/processor/k8sattributesprocessor v0.128.0
  - gomod: go.opentelemetry.io/collector/processor/memorylimiterprocessor v0.128.0
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/processor/transformprocessor v0.128.0

receivers:
  - gomod: go.opentelemetry.io/collector/receiver/otlpreceiver v0.129.0
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/receiver/k8sclusterreceiver v0.128.0
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/receiver/k8seventsreceiver v0.128.0
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/receiver/kubeletstatsreceiver v0.128.0

extensions:
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/extension/healthcheckextension v0.128.0