# builder-config.yaml
dist:
  name: custom-otelcol
  description: Custom OpenTelemetry Collector
  output_path: ./custom-collector
  otelcol_version: 0.91.0

exporters:
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/exporter/debugexporter v0.91.0
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/exporter/otlphttpexporter v0.91.0
  - gomod: go.opentelemetry.io/collector/exporter/otlpexporter v0.91.0

processors:
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/processor/batchprocessor v0.91.0
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/processor/k8sattributesprocessor v0.91.0
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/processor/memorylimiterprocessor v0.91.0
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/processor/transformprocessor v0.91.0

receivers:
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/receiver/k8sclusterreceiver v0.91.0
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/receiver/k8seventsreceiver v0.91.0
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/receiver/kubeletstatsreceiver v0.91.0
  - gomod: go.opentelemetry.io/collector/receiver/otlpreceiver v0.91.0

extensions:
  - gomod: go.opentelemetry.io/collector/extension/healthcheckextension v0.91.0
  - gomod: go.opentelemetry.io/collector/extension/pprofextension v0.91.0